"""Add created_at and updated_at to categories

Revision ID: 484e5ad04427
Revises: 91ecfdeea560
Create Date: 2025-09-01 14:01:48.908564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '484e5ad04427'
down_revision: Union[str, Sequence[str], None] = '91ecfdeea560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
