"""update  categories table

Revision ID: 5a46a2b89a39
Revises: c84b0a138d8d
Create Date: 2025-09-01 14:44:20.307647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a46a2b89a39'
down_revision: Union[str, Sequence[str], None] = 'c84b0a138d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('deleted_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'deleted_by')
    op.drop_column('categories', 'updated_by')
    op.drop_column('categories', 'created_by')
    # ### end Alembic commands ###
